### ISSUE TITLE
Maven project doesn't compile

### ISSUE THREAD

**Issue by frankydee** [SmartBear/soapui#413]
I have just cloned the project, followed the instructions in README.md and `mvn clean install` fails with the following error:

```bash
[ERROR] Failed to execute goal on project soapui: Could not resolve dependencies for project com.smartbear.soapui:soapui:jar:5.5.0-SNAPSHOT: The following artifacts could not be resolved: com.smartbear.utils.analytics:analytics-core:jar:5.5.0-SNAPSHOT, com.smartbear.utils.analytics:out-app-analytics-provider:jar:5.5.0-SNAPSHOT: Failure to find com.smartbear.utils.analytics:analytics-core:jar:5.5.0-SNAPSHOT in http://www.soapui.org/repository/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of smartbear-sweden-repository has elapsed or updates are forced -> [Help 1]
```

Here is a copy of the full commands I executed:

```bash
Home@thinkpad MINGW64 /c/Users/home/code
$ git clone https://github.com/SmartBear/soapui.git
Cloning into 'soapui'...
remote: Enumerating objects: 683, done.
remote: Counting objects: 100% (683/683), done.
remote: Compressing objects: 100% (363/363), done.
Receiving objects: 100% (132727/132727), 93.58 MiB | 1.21 MiB/s, done.
remote: Total 132727 (delta 358), reused 506 (delta 242), pack-reused 132044
Resolving deltas: 100% (86074/86074), done.
Checking out files: 100% (3122/3122), done.

Home@thinkpad MINGW64 /c/Users/home/code
$ cd soapui/

Home@thinkpadMINGW64 /c/Users/home/code/soapui (next)
$ mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] SoapUI project
[INFO] SoapUI
[INFO] SoapUI Maven plugin
[INFO] SoapUI installer
[INFO] SoapUI Maven plugin tester
[INFO] SoapUI system test
[INFO] soapui-testserver-api
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building SoapUI project 5.5.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ soapui-project ---
[INFO] Deleting C:\Users\home\code\soapui (includes = [*.log], excludes = [])
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-versions) @ soapui-project ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-bytecode-version) @ soapui-project ---
[INFO]
[INFO] --- animal-sniffer-maven-plugin:1.15:check (animal-sniffer-check) @ soapui-project ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java18:1.0
Downloading from smartbear-sweden-repository: http://www.soapui.org/repository/maven2/org/codehaus/mojo/signature/java18/1.0/java18-1.0.signature
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/signature/java18/1.0/java18-1.0.signature
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/signature/java18/1.0/java18-1.0.signature (2.0 MB at 922 kB/s)
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ soapui-project ---
[INFO] Installing C:\Users\home\code\soapui\pom.xml to C:\Users\home\.m2\repository\com\smartbear\soapui\soapui-project\5.5.0-SNAPSHOT\soapui-project-5.5.0-SNAPSHOT.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building SoapUI 5.5.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.smartbear.utils.analytics:analytics-core:jar:5.5.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.smartbear.utils.analytics:out-app-analytics-provider:jar:5.5.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] SoapUI project ..................................... SUCCESS [  7.321 s]
[INFO] SoapUI ............................................. FAILURE [  1.564 s]
[INFO] SoapUI Maven plugin ................................ SKIPPED
[INFO] SoapUI installer ................................... SKIPPED
[INFO] SoapUI Maven plugin tester ......................... SKIPPED
[INFO] SoapUI system test ................................. SKIPPED
[INFO] soapui-testserver-api .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.213 s
[INFO] Finished at: 2019-02-03T15:51:50+01:00
[INFO] Final Memory: 15M/174M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project soapui: Could not resolve dependencies for project com.smartbear.soapui:soapui:jar:5.5.0-SNAPSHOT: The following artifacts could not be resolved: com.smartbear.utils.analytics:analytics-core:jar:5.5.0-SNAPSHOT, com.smartbear.utils.analytics:out-app-analytics-provider:jar:5.5.0-SNAPSHOT: Failure to find com.smartbear.utils.analytics:analytics-core:jar:5.5.0-SNAPSHOT in http://www.soapui.org/repository/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of smartbear-sweden-repository has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :soapui
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0

```

My environment details:

OS: Windows 7
Java: 
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

**Comment by IlyaAvdeev** [comment]
Hi, sorry for inconviniences, please use 5.4.0 for the mentioned artifacts atm, right after release we'll fix it on our end.

**Comment by nmrao** [comment]
Looks maven repo url might got changed as it could not find the analytics at the url mentioned in the current pom file

**Comment by nmrao** [comment]
Found this new maven repo url, give it a try
http://smartbearsoftware.com/repository/maven2

**Comment by frankydee** [comment]
Thank you @IlyaAvdeev, branch `remotes/origin/release-5.4.0` does compile.  I'll use that in the meantime.  Please leave this issue open until the `next` branch compiles.

@nmrao, thanks for the tip but that didn't work.  The current `pom.xml` URL (http://www.soapui.org/repository/maven2) already redirects to http://smartbearsoftware.com/repository/maven2 so it made no difference.

**Comment by nmrao** [comment]
What error do you get? The same or new error?

**Comment by frankydee** [comment]
Same, analytics jars missing.

**Comment by nmrao** [comment]
If you look at the above maven repository, there is file available, analytics-core-5.5.0.jar, but the name does not have 'SNAPSHOT' in it which is what maven is looking for.

**Comment by IlyaAvdeev** [comment]
Hang on, I'll deploy 5.4.0-SNAPSHOT

**Comment by IlyaAvdeev** [comment]
I'll deploy 5.5.0-SNAPSHOT soon, but I advise to use release-5.5.0 branch, since it will be released soon and contains the latest bug fixes and features

**Comment by IlyaAvdeev** [comment]
Should be fixed now for "next" branch, but I still suggest to focus on release-.5.5.0 branch :)

**Comment by lhanson** [comment]
FYI I just tried a rebuild, looks like I'm still unable to resolve the snapshot.

https://gist.github.com/lhanson/84640e735a09dbc1ccf6af85284836f2

**Comment by IlyaAvdeev** [comment]
what about release-5.5.0 branch?

**Comment by nmrao** [comment]
> FYI I just tried a rebuild, looks like I'm still unable to resolve the snapshot.
> 
> https://gist.github.com/lhanson/84640e735a09dbc1ccf6af85284836f2

Looks there is another dependency, 'out-app-analytics-provider' has similar problem as 'analytics-core'

**Comment by lhanson** [comment]
> what about release-5.5.0 branch?

release-5.5.0 branch builds successfully for me.

**Comment by nmrao** [comment]
Thank you for that @lhanson .
I was just following the readme. 
So, building 5.5.0 needs change in main pom.xml. Correct?

**Comment by lhanson** [comment]
> So, building 5.5.0 needs change in main pom.xml. Correct?

I was able to build `release-5.5.0` without any changes. As far as I can tell, the only issue with the `next` branch is a missing `com.smartbear.utils.analytics:out-app-analytics-provider:jar:5.5.0-SNAPSHOT`.

**Comment by IlyaAvdeev** [comment]
please pull the latest changes for the "next" branch and try to build.

**Comment by lhanson** [comment]
Works now, thanks @IlyaAvdeev .

**Comment by IlyaAvdeev** [comment]
Thank you for help, closing the issue

**Comment by MalcolmAnderson** [comment]
I'm having a problem building latest, release 5.5, and release 5.4
I'm not sure where I should start explaining stuff without wasting a lot of time.
Should I write up 3 different bugs, or should I continue working in this closed inc?

**Comment by MalcolmAnderson** [comment]
Here are the errors that I'm getting attempting to run 
mvn clean install on the next branch
Am I doing something wrong?

[next_branch_failed_build.txt](https://github.com/SmartBear/soapui/files/3113687/next_branch_failed_build.txt)

**Comment by IlyaAvdeev** [comment]
Tomorrow I'll add required dependencies. Right now you can update manually 
com.smartbear.utils.analytics:analytics-core:jar:5.6.0-SNAPSHOT
com.smartbear.utils.analytics:out-app-analytics-provider:jar:5.6.0-SNAPSHOT
down to 5.5.0. this should work.
